theme: jekyll-theme-slate
title: Personal webpage of Pradyumna Chari, PhD candidate at the Visual Machines Group, University of California, Los Angeles.
description: PhD candidate at the Visual Machines Group, University of California, Los Angeles.
